version: '3'
services:
  app:
    build: docker/php
    container_name: skillup_app_new
    volumes:
      - ./:/var/www
    depends_on:
      - db
  nginx:
    image: nginx:1.17
    container_name: skillup_nginx_new
    ports:
      - 8888:80
      - 3000:3000
    volumes:
      - ./:/var/www
      - ./docker/nginx/lara.skillup.local.conf:/etc/nginx/conf.d/lara.skillup.local.conf
    depends_on:
      - app
  db:
    image: mysql:8.0.23
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./docker/mysql/lara:/var/lib/mysql
    container_name: lara_mysql_new
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: lara_db
      MYSQL_USER: lara_user
      MYSQL_PASSWORD: lara_pwd
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8012:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=skillup-pma.local
